name: Build Kivy APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          openjdk-17-jdk \
          unzip \
          zip \
          autoconf \
          libtool \
          pkg-config \
          libncurses5:amd64 \
          libstdc++6:amd64 \
          libgtk2.0-0:amd64 \
          libpangox-1.0-0:amd64 \
          libpangoxft-1.0-0:amd64 \
          libidn11:amd64 \
          python3-pip \
          python3-dev
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses || true
        sdkmanager --update
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade buildozer
        pip install --upgrade cython==0.29.36
        pip install --upgrade virtualenv
    
    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.gradle
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          buildozer-global-
    
    - name: Cache Buildozer directory
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: buildozer-local-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          buildozer-local-
    
    - name: Make buildozer directory writable
      run: |
        mkdir -p ~/.buildozer
        sudo chmod -R 777 ~/.buildozer || true
        mkdir -p .buildozer
        sudo chmod -R 777 .buildozer || true
    
    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
      env:
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        ANDROID_HOME: /usr/local/lib/android/sdk
    
    - name: List output files
      if: always()
      run: |
        echo "Contents of bin directory:"
        ls -la bin/ || echo "No bin directory"
        echo "Contents of .buildozer:"
        find .buildozer -name "*.apk" || echo "No APK files found"
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: kivy-app-debug-${{ github.sha }}
        path: bin/*.apk
        retention-days: 30
    
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}